// Note: Resume generation is handled in the Electron main process
// This file is kept for reference but the actual implementation
// is in electron/resume-generator.ts

import OpenAI from 'openai';

export interface ProfileData {
  workHistory: any[];
  skills: string[];
  education: any[];
  personalInfo: any;
}

// Helper function to format dates to MM/YYYY
function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  // If already in MM/YYYY format, return as is
  if (/^\d{2}\/\d{4}$/.test(dateStr)) {
    return dateStr;
  }
  // Try to parse and format
  const date = new Date(dateStr);
  if (!isNaN(date.getTime())) {
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const year = date.getFullYear();
    return `${month}/${year}`;
  }
  return dateStr;
}

// Helper function to parse date and get year
function getYearFromDate(dateStr: string): number | null {
  if (!dateStr) return null;
  // If in MM/YYYY format
  if (/^\d{2}\/\d{4}$/.test(dateStr)) {
    return parseInt(dateStr.split("/")[1]);
  }
  // Try to parse as date
  const date = new Date(dateStr);
  if (!isNaN(date.getTime())) {
    return date.getFullYear();
  }
  return null;
}

// Build base resume structure with preserved factual data
function buildBaseResumeStructure(profileData: ProfileData, ageOptimized: boolean = false): any {
  // Build personal info - preserve exactly
  const personalInfo = {
    name: profileData.personalInfo?.firstName && profileData.personalInfo?.lastName
      ? `${profileData.personalInfo.firstName} ${profileData.personalInfo.lastName}`
      : profileData.personalInfo?.name || "",
    email: profileData.personalInfo?.email || "",
    phone: profileData.personalInfo?.phone || "",
    location: profileData.personalInfo?.location || "",
  };

  // Build work experience - preserve company names, positions, dates exactly
  let workHistory = profileData.workHistory || [];
  
  // For age-optimized resumes, filter to last 15 years of experience
  if (ageOptimized) {
    const currentYear = new Date().getFullYear();
    const cutoffYear = currentYear - 15;
    
    workHistory = workHistory.filter((work: any) => {
      const startYear = getYearFromDate(work.startDate || "");
      const endYear = work.endDate ? getYearFromDate(work.endDate) : currentYear;
      
      // Include if job ended within last 15 years or is still ongoing
      // This ensures we keep recent/relevant experience
      return (endYear && endYear >= cutoffYear) || !endYear;
    });
  }

  const workExperience = workHistory.map((work: any) => ({
    title: work.position || work.title || "", // Preserve exactly
    company: work.company || "", // Preserve exactly including LLC, Inc., etc.
    startDate: formatDate(work.startDate || ""),
    endDate: work.endDate ? formatDate(work.endDate) : "Present",
    description: work.description || "", // Will be enhanced by AI
  }));

  // Build education - preserve exactly
  // For age-optimized resumes, remove graduation dates (they can reveal age)
  const education = (profileData.education || []).map((edu: any) => ({
    degree: edu.degree || "",
    school: edu.institution || edu.school || "",
    field: edu.field || "",
    graduationDate: ageOptimized ? "" : (edu.graduationDate ? formatDate(edu.graduationDate) : ""), // Remove dates for age optimization
  }));

  // Preserve skills exactly as provided
  const skills = [...(profileData.skills || [])];

  return {
    personalInfo,
    workExperience,
    education,
    skills,
    summary: "", // Will be generated by AI
  };
}

export async function generateResumeContent(
  profileData: ProfileData,
  jobType: string,
  ageOptimized: boolean = false,
  apiKey?: string
): Promise<any> {
  try {
    // This function is not used in the renderer - actual implementation is in electron/resume-generator.ts
    // This is kept for type reference only
    if (!apiKey) {
      throw new Error('API key required');
    }
    const openai = new OpenAI({ apiKey });

    // Build base structure with all factual data preserved
    const baseResume = buildBaseResumeStructure(profileData, ageOptimized);

    const isGeneral = jobType === "General";
    
    // Age optimization instructions
    const ageOptimizationInstructions = ageOptimized ? `
    
AGE OPTIMIZATION MODE - CRITICAL INSTRUCTIONS:
- MODERNIZE ALL LANGUAGE: Use contemporary, current industry terminology. Avoid dated phrases or old-fashioned language.
- FOCUS ON RECENT EXPERIENCE: Emphasize the most recent work experiences (last 10-15 years) in descriptions and summary.
- REMOVE AGE INDICATORS: Do not mention "years of experience" with specific numbers that might reveal age. Use phrases like "extensive experience" or "proven track record" instead.
- CONTEMPORARY TONE: Write in a fresh, modern, energetic tone that sounds current and forward-thinking.
- SKILLS-FOCUSED: Emphasize skills and achievements over chronological history.
- REMOVE OUTDATED REFERENCES: Do not reference old technologies, methodologies, or industry terms that are clearly outdated.
` : "";

    const prompt = isGeneral
      ? `You are an expert resume writer. Your task is to enhance ONLY the descriptions and create a professional summary. ALL factual data has already been preserved and will be merged back.
${ageOptimizationInstructions}
CRITICAL: You are ONLY enhancing descriptions and creating a summary. DO NOT return company names, job titles, dates, personal info, skills, or education - these are already preserved.

Your task:
1. CREATE A PROFESSIONAL SUMMARY: Write a compelling 3-4 sentence summary that highlights the candidate's key strengths${ageOptimized ? ", proven expertise, and unique value proposition" : ", years of experience, and unique value proposition"}. Use powerful, confident language${ageOptimized ? " with a modern, contemporary tone" : ""}.

2. ENHANCE WORK EXPERIENCE DESCRIPTIONS: For each work experience, enhance the description field only:
   - Convert plain descriptions into achievement-focused bullet points
   - Use strong, modern action verbs (Led, Developed, Implemented, Optimized, Increased, etc.)${ageOptimized ? " - prefer contemporary, current industry terminology" : ""}
   - Add quantifiable results where possible (percentages, numbers, scale)
   - Make responsibilities sound more impactful and professional
   - Focus on achievements and outcomes, not just duties${ageOptimized ? "\n   - For older positions, emphasize transferable skills and modern relevance rather than dated specifics" : ""}

3. ENHANCE EDUCATION DESCRIPTIONS: Make education descriptions sound more professional and highlight relevant coursework or achievements if applicable.

Base Resume Structure (factual data already preserved):
${JSON.stringify(baseResume, null, 2)}

Return a JSON object with ONLY these fields:
{
  "summary": "A compelling, professional 3-4 sentence summary that makes the candidate sound impressive",
  "workExperience": [
    {
      "description": "Enhanced, professional description with action verbs and achievements"
    }
  ],
  "education": [
    {
      "description": "Enhanced education description (if applicable)"
    }
  ]
}

IMPORTANT: 
- Return ONLY the summary and enhanced descriptions
- DO NOT include personalInfo, company names, job titles, dates, or skills in your response
- These will be merged with the preserved factual data
- Return only valid JSON.`
      : `You are an expert resume writer. Your task is to enhance ONLY the descriptions and create a professional summary optimized for ${jobType} positions. ALL factual data has already been preserved and will be merged back.
${ageOptimizationInstructions}
CRITICAL: You are ONLY enhancing descriptions and creating a summary. DO NOT return company names, job titles, dates, personal info, skills, or education - these are already preserved.

Your task:
1. CREATE A TARGETED PROFESSIONAL SUMMARY: Write a compelling 3-4 sentence summary specifically tailored for ${jobType} roles, highlighting relevant experience and skills${ageOptimized ? " with a modern, contemporary tone" : ""}.

2. ENHANCE WORK EXPERIENCE DESCRIPTIONS: For each work experience, enhance the description field only, emphasizing relevance to ${jobType}:
   - Convert plain descriptions into achievement-focused bullet points
   - Use strong, modern action verbs (Led, Developed, Implemented, Optimized, Increased, etc.)${ageOptimized ? " - prefer contemporary, current industry terminology" : ""}
   - Emphasize experiences most relevant to ${jobType} roles${ageOptimized ? " - prioritize recent experiences" : ""}
   - Add quantifiable results where possible
   - Make responsibilities sound more impactful and professional
   - Focus on achievements and outcomes relevant to ${jobType}${ageOptimized ? "\n   - For older positions, emphasize transferable skills and modern relevance rather than dated specifics" : ""}

3. ENHANCE EDUCATION DESCRIPTIONS: Make education descriptions sound professional and highlight any coursework or achievements relevant to ${jobType}.

Base Resume Structure (factual data already preserved):
${JSON.stringify(baseResume, null, 2)}

Return a JSON object with ONLY these fields:
{
  "summary": "A compelling, professional summary tailored for ${jobType} roles",
  "workExperience": [
    {
      "description": "Enhanced, professional description with action verbs and achievements relevant to ${jobType}"
    }
  ],
  "education": [
    {
      "description": "Enhanced education description (if applicable)"
    }
  ]
}

IMPORTANT: 
- Return ONLY the summary and enhanced descriptions
- DO NOT include personalInfo, company names, job titles, dates, or skills in your response
- These will be merged with the preserved factual data
- Return only valid JSON.`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are an expert resume writer with 20+ years of experience. Your specialty is transforming raw information into polished, professional resumes that sound impressive and compelling. You excel at using strong action verbs, achievement-focused language, and industry-standard terminology to make candidates stand out.${ageOptimized ? " SPECIAL FOCUS: You specialize in creating age-optimized resumes that emphasize modern skills, contemporary language, and recent achievements while maintaining professionalism and truthfulness." : ""} CRITICAL RULE: You must preserve ALL factual information EXACTLY as provided - company names (including LLC, Inc., Corp., etc.), job titles/positions, personal information, dates, institution names, degree names. NEVER change, shorten, remove suffixes, or 'improve' factual data. Only enhance descriptions and summaries - factual data must remain identical to the source.`,
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      response_format: { type: "json_object" },
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error("Failed to generate resume content - no response from OpenAI");
    }

    try {
      const aiEnhancements = JSON.parse(content);
      
      // Log for debugging
      console.log("Profile data received:", {
        workHistoryCount: profileData.workHistory?.length || 0,
        skillsCount: profileData.skills?.length || 0,
        skills: profileData.skills,
      });
      
      // Merge AI enhancements with preserved factual data
      const finalResume = {
        personalInfo: baseResume.personalInfo, // Preserved exactly
        summary: aiEnhancements.summary || "",
        workExperience: baseResume.workExperience.map((exp: any, index: number) => {
          // Find matching enhancement by index or by company/title match
          const enhancement = aiEnhancements.workExperience?.[index];
          return {
            ...exp, // Preserve all factual data (title, company, dates) - NEVER change these
            description: enhancement?.description || exp.description || "",
          };
        }),
        education: baseResume.education.map((edu: any, index: number) => ({
          ...edu, // Preserve all factual data
          description: aiEnhancements.education?.[index]?.description || "",
        })),
        skills: baseResume.skills, // Preserved exactly - use ALL skills from profile
      };

      console.log("Final resume structure:", {
        workExperienceCount: finalResume.workExperience.length,
        skillsCount: finalResume.skills.length,
        skills: finalResume.skills,
        companies: finalResume.workExperience.map((e: any) => e.company),
      });

      return finalResume;
    } catch (parseError) {
      console.error("Failed to parse OpenAI response:", content);
      throw new Error("Failed to parse resume content from AI response");
    }
  } catch (error) {
    console.error("Error in generateResumeContent:", error);
    if (error instanceof Error) {
      throw error;
    }
    throw new Error("Unknown error occurred while generating resume");
  }
}

